### ISSUE TITLE
Regarding the performance results

### ISSUE THREAD

**Issue by NamelessGaki** [wkq-wukaiqi/Face-X-Ray#1]
Hello,

Thanks for your work. I have one question regarding your implementation, did you succeed in reproducing the results of the original paper?
If so, can you please add a table to your ReadMe where you add your results?

Thank you :)

**Comment by wkq-wukaiqi** [comment]
Hello,

When I trained my model using only blended images in sec 3.2 of the paper, I achieved AUC 99.252, 96.276, 98.666, 96.408 on DF, F2F, FS, NT, respectively. Perhaps some details were missed in data preprocessing or training, resulting in a lower AUC. I will update my result soon.

Thank you for your issue~
